// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD5wQsNHSS805uXZdnE5KUG8Li_yo_NxI',
    appId: '1:524194236986:web:8da370cd400b5570020303',
    messagingSenderId: '524194236986',
    projectId: 'spotify33',
    authDomain: 'spotify33.firebaseapp.com',
    storageBucket: 'spotify33.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZKt7OhSMYF3FmWlKyLZZhNmsWAoNDNrY',
    appId: '1:524194236986:android:77a00e81b1b2eaa5020303',
    messagingSenderId: '524194236986',
    projectId: 'spotify33',
    storageBucket: 'spotify33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbHhn9fsoLDJVeMWNeG3upovPMFgOkIzA',
    appId: '1:524194236986:ios:f494d4baea907ab6020303',
    messagingSenderId: '524194236986',
    projectId: 'spotify33',
    storageBucket: 'spotify33.appspot.com',
    iosBundleId: 'com.example.spotify',
  );
}
